# Background and foreground colors
background = #f5f1ea
foreground = #111111

# Standard colors
palette = 0=#f5f1ea
palette = 1=#f2477c
palette = 2=#32c24a
palette = 3=#f5a000
palette = 4=#00c2ee
palette = 5=#c550fb
palette = 6=#00c6c6
palette = 7=#111111

# Bright colors
palette = 8=#958e84
palette = 9=#ff5f87
palette = 10=#5fd75f
palette = 11=#ffc14a
palette = 12=#4ad2ff
palette = 13=#d787ff
palette = 14=#5fd7d7
palette = 15=#0b0b0b
