$color = rgba(255, 255, 255, 1)
$inner_color = rgba(255, 255, 255, 0.66)
$outer_color = rgba(175, 95, 215, 1)
$font_color = rgba(28, 28, 28, 1)
$placeholder_color = rgba(28, 28, 28, 0.7)
$check_color = rgba(0, 175, 175, 1)
