$color = rgba(245, 241, 234, 1)
$inner_color = rgba(245, 241, 234, 0.66)
$outer_color = rgba(197, 80, 251, 1)
$font_color = rgba(17, 17, 17, 1)
$placeholder_color = rgba(17, 17, 17, 0.7)
$check_color = rgba(0, 198, 198, 1)
