background            #f5f1ea
foreground            #111111

# black
color0  #f5f1ea
color8  #958e84

# red
color1  #f2477c
color9  #ff5f87

# green
color2  #32c24a
color10 #5fd75f

# yellow
color3  #f5a000
color11 #ffc14a

# blue
color4  #00c2ee
color12 #4ad2ff

# magenta
color5  #c550fb
color13 #d787ff

#cyan
color6  #00c6c6
color14 #5fd7d7

#white
color7  #111111
color15 #0b0b0b
